services:
  # API FastAPI
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: diabetes-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - diabetes-network

  # Dashboard Streamlit
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: diabetes-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - diabetes-network

networks:
  diabetes-network:
    driver: bridge

volumes:
  data_volume:
  models_volume: